### ISSUE TITLE
RPC API Calls such as pypresence not working

### ISSUE THREAD

**Issue by jdgwf** [snapcrafters/discord#42]
https://github.com/qwertyquerty/pypresence 

Plugin using API works well via installed .deb, but not in snap. Tried the following in snap, but still got a file not found error

![image](https://user-images.githubusercontent.com/316824/45513235-c9cd7580-b767-11e8-9c0b-16569adc4f84.png)

After some research I found some snap plugins which opened up a few more permissions, which did not work - at least with Ubuntu 18.04 (since it's referencing Unity, I assume this worked on earlier versions).
`snap connect discord:system-observe :system-observe
snap connect discord:unity7 :unity7`

Plugin in question is: https://github.com/ToppleKek/discord-rhythmbox-plugin which works perfectly if .deb is installed.

System is Ubuntu 18.04

**Comment by Simon-Laux** [comment]
I guess we need to find the right plug/interface for allowing rpc

**Comment by Simon-Laux** [comment]
I guess this has something to do with it:
```
Application server failed { Error: listen EPERM /run/user/1000/snap.discord/discord.sock
    at Server.setupListenHandle [as _listen2] (net.js:1286:14)
    at listenInCluster (net.js:1334:12)
    at Server.listen (net.js:1432:5)
    at listenForArgumentsFromNewProcess (/snap/discord/93/usr/share/discord/resources/app.asar/app_bootstrap/singleInstance.js:68:10)
    at tryStart (/snap/discord/93/usr/share/discord/resources/app.asar/app_bootstrap/singleInstance.js:109:20)
    at tryStart (/snap/discord/93/usr/share/discord/resources/app.asar/app_bootstrap/singleInstance.js:79:5)
    at Object.create (/snap/discord/93/usr/share/discord/resources/app.asar/app_bootstrap/singleInstance.js:108:3)
    at App.startApp (/snap/discord/93/usr/share/discord/resources/app.asar/app_bootstrap/bootstrap.js:116:20)
    at Object.onceWrapper (events.js:273:13)
    at App.emit (events.js:187:15)
  errno: 'EPERM',
  code: 'EPERM',
  syscall: 'listen',
  address: '/run/user/1000/snap.discord/discord.sock',
  port: -1 }
```

**Comment by jdgwf** [comment]
Closing ancient issue.
